apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: app1 
    image: supergiantkir/animals:bear
    port: 80
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /app-storage
  - name: app2 
    image: yanivomc/spring-music:latest
    port: 8080
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /app-storage
  volumes:
  hostPath:
  - name: app-storage
    path: /tmp/files
    type: DirectoryOrCreate
  
